# Generated by Django 4.1.3 on 2023-06-21 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mhub', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactForm',
        ),
    ]
