# Generated by Django 4.1.3 on 2023-06-21 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mhub', '0003_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmartContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field1', models.CharField(max_length=100)),
                ('field2', models.IntegerField()),
                ('field3', models.BooleanField()),
            ],
        ),
    ]
