# Generated by Django 4.1.3 on 2023-06-21 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mhub', '0004_smartcontract'),
    ]

    operations = [
        migrations.RenameField(
            model_name='smartcontract',
            old_name='field2',
            new_name='claimedCount',
        ),
        migrations.RenameField(
            model_name='smartcontract',
            old_name='field3',
            new_name='isClaimingEnabled',
        ),
        migrations.RenameField(
            model_name='smartcontract',
            old_name='field1',
            new_name='referalReward',
        ),
    ]
