# Generated by Django 4.1.3 on 2023-06-21 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mhub', '0005_rename_field2_smartcontract_claimedcount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smartcontract',
            name='claimedCount',
            field=models.CharField(max_length=100),
        ),
    ]
