# Generated by Django 4.1.3 on 2023-06-21 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mhub', '0006_alter_smartcontract_claimedcount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smartcontract',
            name='isClaimingEnabled',
            field=models.BooleanField(null=True),
        ),
    ]
