# Generated by Django 4.1.3 on 2023-06-21 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mhub', '0008_airdrop'),
    ]

    operations = [
        migrations.RenameField(
            model_name='smartcontract',
            old_name='claimedCount',
            new_name='claimedSupply',
        ),
    ]
