# Generated by Django 4.1.3 on 2023-06-23 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mhub', '0009_rename_claimedcount_smartcontract_claimedsupply'),
    ]

    operations = [
        migrations.CreateModel(
            name='Airdrop2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_address', models.CharField(max_length=100)),
                ('referral_address', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Airdrop',
        ),
    ]
