# Generated by Django 4.1.3 on 2023-07-23 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mhub', '0011_alter_airdrop2_referral_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='smartcontract',
            old_name='referalReward',
            new_name='totalSupply',
        ),
    ]
