# Generated by Django 4.1.3 on 2023-07-23 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mhub', '0012_rename_referalreward_smartcontract_totalsupply'),
    ]

    operations = [
        migrations.RenameField(
            model_name='smartcontract',
            old_name='isClaimingEnabled',
            new_name='isClaimingPaused',
        ),
        migrations.RenameField(
            model_name='smartcontract',
            old_name='claimedSupply',
            new_name='owner',
        ),
    ]
